"""Project-wide source address constants"""

# vcan2
SOURCE_ADDRESS_0 = x00
SOURCE_ADDRESS_1 = xF0
SOURCE_ADDRESS_2 = x1C
SOURCE_ADDRESS_3 = x05
SOURCE_ADDRESS_4 = x1E

# vcan0
SOURCE_ADDRESS_5 = x8C
SOURCE_ADDRESS_6 = x13
SOURCE_ADDRESS_7 = x22
SOURCE_ADDRESS_8 = xC5
SOURCE_ADDRESS_9 = x47